server:
  port: 8010
management:
  port: 3010
  context-path: /turbine
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
          connection:
            autocommit: true
  thymeleaf:
    prefix: classpath:/templates/
hystrix:
  command:
    default:
     execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
ribbon:
  OkToRetryOnAllOperations: false
  ReadTimeout: 30000
  ConnectTimeout: 30000